export const COMMERCIAL_BANKS = [
  'Access Bank',
  'Citibank Nigeria',
  'Ecobank Nigeria',
  'Fidelity Bank',
  'First Bank of Nigeria',
  'First City Monument Bank (FCMB)',
  'Globus Bank',
  'Guaranty Trust Bank (GTBank)',
  'Heritage Bank',
  'Jaiz Bank',
  'Keystone Bank',
  'Lotus Bank',
  'Optimum Bank',
  'Parallex Bank',
  'Polaris Bank',
  'Premium Trust Bank',
  'Providus Bank',
  'Stanbic IBTC Bank',
  'Standard Chartered Bank',
  'Sterling Bank',
  'SunTrust Bank',
  'Taj Bank',
  'Titan Trust Bank',
  'Union Bank of Nigeria',
  'United Bank for Africa (UBA)',
  'Unity Bank',
  'Wema Bank',
  'Zenith Bank',
];

export const MICROFINANCE_BANKS = [
  'Abbey Microfinance Bank',
  'Above Only Microfinance Bank',
  'Abucoop Microfinance Bank',
  'Accion Microfinance Bank',
  'Addosser Microfinance Bank',
  'Aella Microfinance Bank',
  'Afekhafe Microfinance Bank',
  'Aku Microfinance Bank',
  'Al-Barakah Microfinance Bank',
  'Alekun Microfinance Bank',
  'Ampersand Microfinance Bank',
  'Apeks Microfinance Bank',
  'Archerwood Microfinance Bank',
  'Assets Microfinance Bank',
  'Astra Polaris Microfinance Bank',
  'AVIC Microfinance Bank',
  'Awa Microfinance Bank',
  'Azman Microfinance Bank',
  'Baobab Microfinance Bank',
  'BC Kash Microfinance Bank',
  'Bishopgate Microfinance Bank',
  'Blue Investments Microfinance Bank',
  'Boctaves Microfinance Bank',
  'Bosak Microfinance Bank',
  'BOW Microfinance Bank',
  'Branch Microfinance Bank',
  'Bridgeway Microfinance Bank',
  'Brightway Microfinance Bank',
  'CashConnect Microfinance Bank',
  'Cedar Microfinance Bank',
  'Changan RTS Microfinance Bank',
  'Chibueze Microfinance Bank',
  'Chikum Microfinance Bank',
  'Citizen Trust Microfinance Bank',
  'Confiance Microfinance Bank',
  'Cooperative Microfinance Bank',
  'Coronation Microfinance Bank',
  'Covenant Microfinance Bank',
  'Credit Afrique Microfinance Bank',
  'Crescent Microfinance Bank',
  'Dala Microfinance Bank',
  'Davodani Microfinance Bank',
  'Daystar Microfinance Bank',
  'Delta Trust Microfinance Bank',
  'Diamond Microfinance Bank',
  'Eagle Flight Microfinance Bank',
  'E-Barcs Microfinance Bank',
  'Eco Microfinance Bank',
  'EdFin Microfinance Bank',
  'Ekle Microfinance Bank',
  'Emerald Microfinance Bank',
  'Empire Microfinance Bank',
  'Enrich Microfinance Bank',
  'Esan Microfinance Bank',
  'Esofe Microfinance Bank',
  'ETECH Microfinance Bank',
  'Evangel Microfinance Bank',
  'Evergreen Microfinance Bank',
  'Fairmoney Microfinance Bank',
  'Faith Microfinance Bank',
  'Fast Microfinance Bank',
  'FBNQuest Microfinance Bank',
  'FCMB Microfinance Bank',
  'Fina Trust Microfinance Bank',
  'First Multiple Microfinance Bank',
  'First Royal Microfinance Bank',
  'First Trust Microfinance Bank',
  'FLO Microfinance Bank',
  'Fortress Microfinance Bank',
  'Full Range Microfinance Bank',
  'FundQuest Microfinance Bank',
  'Gateway Microfinance Bank',
  'Gigi Microfinance Bank',
  'GIRE Microfinance Bank',
  'GoodNews Microfinance Bank',
  'Green Bank Microfinance Bank',
  'Grooming Microfinance Bank',
  'GTI Microfinance Bank',
  'Hackman Microfinance Bank',
  'Haggai Microfinance Bank',
  'Hala Microfinance Bank',
  'Halal Credit Microfinance Bank',
  'Hasal Microfinance Bank',
  'Headway Microfinance Bank',
  'Hedonmark Microfinance Bank',
  'HighStreet Microfinance Bank',
  'Homebase Microfinance Bank',
  'Ibile Microfinance Bank',
  'Ikire Microfinance Bank',
  'Ilaro Microfinance Bank',
  'Ilisan Microfinance Bank',
  'Imowo Microfinance Bank',
  'Infinity Trust Microfinance Bank',
  'Infinity Microfinance Bank',
  'Insight Microfinance Bank',
  'Iperu Microfinance Bank',
  'Irokot Microfinance Bank',
  'Isale Gangan Microfinance Bank',
  'Iwade Microfinance Bank',
  'Iwoama Microfinance Bank',
  'Iyin Ekiti Microfinance Bank',
  'KCMB Microfinance Bank',
  'Kadiri Microfinance Bank',
  'Karishma Microfinance Bank',
  'KCM Microfinance Bank',
  'Kredi Money Microfinance Bank',
  'Kuda Microfinance Bank',
  'LAPO Microfinance Bank',
  'Lavender Microfinance Bank',
  'LBIC Microfinance Bank',
  'LEAD Microfinance Bank',
  'Letshego Microfinance Bank',
  'Light Microfinance Bank',
  'Lighthouse Microfinance Bank',
  'Links Microfinance Bank',
  'Living Trust Microfinance Bank',
  'Lobrem Microfinance Bank',
  'Lovonus Microfinance Bank',
  'Mainland Microfinance Bank',
  'Mainstreet Microfinance Bank',
  'Manny Microfinance Bank',
  'Mayfair Microfinance Bank',
  'Megapraise Microfinance Bank',
  'Meka Microfinance Bank',
  'Mercy Microfinance Bank',
  'Mimshach Microfinance Bank',
  'Mint Finex Microfinance Bank',
  'Mkobo Microfinance Bank',
  'Molusi Microfinance Bank',
  'Monarch Microfinance Bank',
  'Moniepoint Microfinance Bank',
  'Mutual Benefits Microfinance Bank',
  'Mutual Trust Microfinance Bank',
  'Nagarta Microfinance Bank',
  'Nana Microfinance Bank',
  'Nasara Microfinance Bank',
  'Ndiorah Microfinance Bank',
  'New Dawn Microfinance Bank',
  'New Golden Microfinance Bank',
  'New Prudential Microfinance Bank',
  'NIRSAL Microfinance Bank',
  'NPF Microfinance Bank',
  'Nuture Microfinance Bank',
  'Oche Microfinance Bank',
  'Odin Microfinance Bank',
  'Ohafia Microfinance Bank',
  'Okpoga Microfinance Bank',
  'Olabisi Ola Microfinance Bank',
  'Olofin Microfinance Bank',
  'Omiye Microfinance Bank',
  'Omoluabi Savings & Loans',
  'One Microfinance Bank',
  'Opay Microfinance Bank',
  'Oraukwu Microfinance Bank',
  'Page Financials',
  'PalmCoast Microfinance Bank',
  'Pamarctic Microfinance Bank',
  'Palladium Microfinance Bank',
  'Pan African Microfinance Bank',
  'Partick Microfinance Bank',
  'Pathway Microfinance Bank',
  'PatrickGold Microfinance Bank',
  'Pay Attitude Online',
  'Peace Microfinance Bank',
  'Pecan Trust Microfinance Bank',
  'Pefco Microfinance Bank',
  'PEN Microfinance Bank',
  'Peniel Microfinance Bank',
  "People's Microfinance Bank",
  'Phebean Microfinance Bank',
  'Phetanna Microfinance Bank',
  'Pillar Microfinance Bank',
  'Platinum Mortgage Bank',
  'Polaris Microfinance Bank',
  'Premium Microfinance Bank',
  'Presley Microfinance Bank',
  'Prime Microfinance Bank',
  'Pristine Gate Microfinance Bank',
  'Progress Microfinance Bank',
  'Prospa Microfinance Bank',
  'QuickFund Microfinance Bank',
  'Rabana Microfinance Bank',
  'Rahama Microfinance Bank',
  'Rainbow Microfinance Bank',
  'Rajan Microfinance Bank',
  'Rand Merchant Bank',
  'Rapid Microfinance Bank',
  'ReadyCash Microfinance Bank',
  'Regent Microfinance Bank',
  'Reliance Microfinance Bank',
  'RenMoney Microfinance Bank',
  'Rephidim Microfinance Bank',
  'Richway Microfinance Bank',
  'Righteous Microfinance Bank',
  'Rockway Microfinance Bank',
  'Royal Exchange Microfinance Bank',
  'Rubies Microfinance Bank',
  'Safegate Microfinance Bank',
  'Sagamu Microfinance Bank',
  'SAGE-CTU Microfinance Bank',
  'Savannah Microfinance Bank',
  'Seed Capital Microfinance Bank',
  'Seedvest Microfinance Bank',
  'Shared Agent Microfinance Bank',
  'Shield Microfinance Bank',
  'Shongom Microfinance Bank',
  'SL Microfinance Bank',
  'Snow Microfinance Bank',
  'Solidrock Microfinance Bank',
  'Sparkle Microfinance Bank',
  'Spatial Microfinance Bank',
  'Standard Microfinance Bank',
  'Stanford Microfinance Bank',
  'Stellas Microfinance Bank',
  'Stephanos Microfinance Bank',
  'Stockpile Microfinance Bank',
  'Sunbeam Microfinance Bank',
  'Supreme Microfinance Bank',
  'TagPay Microfinance Bank',
  'Tajwal Microfinance Bank',
  'Tangerine Money',
  'Teasy Mobile Money',
  'Testimony Microfinance Bank',
  'Think Money Microfinance Bank',
  'Titan Microfinance Bank',
  'Topaz Microfinance Bank',
  'Trade Core Microfinance Bank',
  'Transnational Microfinance Bank',
  'Trident Microfinance Bank',
  'Trinity Microfinance Bank',
  'Trust Microfinance Bank',
  'Trustbond Microfinance Bank',
  'Trustfund Microfinance Bank',
  'U & C Microfinance Bank',
  'UBA Microfinance Bank',
  'Ummah Microfinance Bank',
  'Unical Microfinance Bank',
  'Uniq Microfinance Bank',
  'Univel Microfinance Bank',
  'VFD Microfinance Bank',
  'Virtue Microfinance Bank',
  'Visa Microfinance Bank',
  'Viva Microfinance Bank',
  'VTNetworks',
  'Wallets Microfinance Bank',
  'Waya Microfinance Bank',
  'Wema Microfinance Bank',
  'Wetland Microfinance Bank',
  'XDS Microfinance Bank',
  'Xpress Microfinance Bank',
  'Yes Microfinance Bank',
  'Yobe Microfinance Bank',
  'Zanaco Microfinance Bank',
  'Zedvance Microfinance Bank',
  'Zenith Microfinance Bank',
];

export const ALL_NIGERIAN_BANKS = [
  ...COMMERCIAL_BANKS,
  ...MICROFINANCE_BANKS,
].sort((a, b) => a.localeCompare(b));
