/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed-variant': '#264679',
        'on-error': '#ffffff',
        'on-secondary-container': '#315084',
        'tertiary-fixed-dim': '#bfc7d4',
        'outline': '#737785',
        'surface-dim': '#dbdad7',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e9e8e5',
        'on-error-container': '#93000a',
        'surface-container': '#efeeeb',
        'on-tertiary-fixed': '#141c26',
        'on-surface': '#1b1c1a',
        'on-secondary-fixed': '#001b3f',
        'background': '#faf9f6',
        'inverse-primary': '#b2c5ff',
        'surface-bright': '#faf9f6',
        'on-tertiary-fixed-variant': '#3f4752',
        'surface-container-low': '#f4f3f0',
        'on-surface-variant': '#424654',
        'tertiary-fixed': '#dbe3f1',
        'secondary-fixed-dim': '#abc7ff',
        'primary-fixed-dim': '#b2c5ff',
        'tertiary-container': '#575f6b',
        'on-tertiary': '#ffffff',
        'surface-tint': '#0056d2',
        'on-primary-fixed-variant': '#0040a1',
        'surface': '#faf9f6',
        'on-primary-fixed': '#001847',
        'tertiary': '#3f4752',
        'inverse-on-surface': '#f2f1ee',
        'secondary-container': '#a6c4ff',
        'on-primary-container': '#ccd8ff',
        'on-tertiary-container': '#d1d9e7',
        'secondary-fixed': '#d7e2ff',
        'primary-container': '#0056d2',
        'on-secondary': '#ffffff',
        'surface-variant': '#e3e2df',
        'secondary': '#405e93',
        'primary': '#0040a1',
        'on-primary': '#ffffff',
        'inverse-surface': '#2f312f',
        'on-background': '#1b1c1a',
        'error': '#ba1a1a',
        'surface-container-highest': '#e3e2df',
        'outline-variant': '#c3c6d6',
        'primary-fixed': '#dae2ff',
        'error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '9999px',
      },
      spacing: {
        'stack-sm': '4px',
        'stack-md': '8px',
        'stack-lg': '16px',
        'container-max': '1128px',
        'card-padding': '20px',
        'gutter': '24px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
